export interface AuditoriaModel {
  id: number,
  id_bien: number,
  cod_patrimonial: string,
  id_tipo_bien: number,
  descripcion: string,
  id_marca: number,
  id_modelo: number,
  n_serie: string,
  n_orden: string,
  fech_orden: string,
  n_nea: string,
  fech_nea: string,
  mayor: string,
  id_sub_cta: number,
  id_sede: number,
  desc_sede: string,
  fecha_movimiento: string,
  fecha_alta: string,
  id_convenio: string,
  convenio: string,
  id_administrado: string,
  administrado: string,
  flg_solicitud: number,
  fech_reg: Date
}
